export const trainData = {
  trainCode: "8903",
  crew: [
    { id: "1", name: "John Smith", role: "Driver", shift: "Day" },
    { id: "2", name: "Sarah Johnson", role: "Conductor", shift: "Day" },
    { id: "3", name: "Mike Brown", role: "Assistant", shift: "Day" },
  ],
  stations: [
    {
      order: 1,
      code: "KAZ",
      name: "KASERNE",
      arrivalTime: "04:54",
      departureTime: "05:06",
      runTime: "00:50",
      accumulativeTime: "00:50",
    },
    {
      order: 3,
      code: "JUP",
      name: "JUPITER",
      arrivalTime: "05:06",
      departureTime: "05:06",
      runTime: "00:12",
      accumulativeTime: "00:12",
    },
    {
      order: 5,
      code: "RFI",
      name: "REFINERY",
      arrivalTime: "05:12",
      departureTime: "05:12",
      runTime: "00:06",
      accumulativeTime: "00:18",
    },
    {
      order: 7,
      code: "IDI",
      name: "INDIA",
      arrivalTime: "05:16",
      departureTime: "05:16",
      runTime: "00:04",
      accumulativeTime: "00:22",
    },
    {
      order: 9,
      code: "GSW",
      name: "GERMISTONWEST",
      arrivalTime: "05:19",
      departureTime: "05:19",
      runTime: "00:03",
      accumulativeTime: "00:25",
    },
    {
      order: 11,
      code: "GMS",
      name: "GERMISTONSOUT",
      arrivalTime: "05:25",
      departureTime: "05:25",
      runTime: "00:06",
      accumulativeTime: "00:31",
    },
    {
      order: 13,
      code: "GRM",
      name: "GERMISTONLAKE",
      arrivalTime: "05:28",
      departureTime: "05:28",
      runTime: "00:03",
      accumulativeTime: "00:34",
    },
    {
      order: 15,
      code: "WBR",
      name: "WEBBER",
      arrivalTime: "05:32",
      departureTime: "05:32",
      runTime: "00:04",
      accumulativeTime: "00:38",
    },
    {
      order: 17,
      code: "PHL",
      name: "PARKHILL",
      arrivalTime: "05:35",
      departureTime: "05:35",
      runTime: "00:03",
      accumulativeTime: "00:41",
    },
    {
      order: 19,
      code: "EBG",
      name: "ELSBURG",
      arrivalTime: "05:38",
      departureTime: "05:38",
      runTime: "00:03",
      accumulativeTime: "00:44",
    },
    {
      order: 21,
      code: "DAA",
      name: "DALLAS",
      arrivalTime: "05:41",
      departureTime: "05:41",
      runTime: "00:03",
      accumulativeTime: "00:47",
    },
    {
      order: 23,
      code: "WTL",
      name: "WATTLES",
      arrivalTime: "05:44",
      departureTime: "05:44",
      runTime: "00:03",
      accumulativeTime: "00:50",
    },
    {
      order: 25,
      code: "UNN",
      name: "UNION",
      arrivalTime: "05:49",
      departureTime: "05:49",
      runTime: "00:05",
      accumulativeTime: "00:55",
    },
    {
      order: 27,
      code: "RDP",
      name: "ROOIKOP",
      arrivalTime: "05:58",
      departureTime: "05:58",
      runTime: "00:09",
      accumulativeTime: "01:04",
    },
    {
      order: 29,
      code: "MPR",
      name: "MAPLETON",
      arrivalTime: "06:07",
      departureTime: "06:07",
      runTime: "00:09",
      accumulativeTime: "01:13",
    },
    {
      order: 31,
      code: "RLL",
      name: "RIETVALLEI",
      arrivalTime: "06:15",
      departureTime: "06:15",
      runTime: "00:08",
      accumulativeTime: "01:21",
    },
    {
      order: 33,
      code: "GNY",
      name: "GLENROY",
      arrivalTime: "06:19",
      departureTime: "06:19",
      runTime: "00:04",
      accumulativeTime: "01:25",
    },
    {
      order: 35,
      code: "DSK",
      name: "DRIEMANSKAP",
      arrivalTime: "06:27",
      departureTime: "06:27",
      runTime: "00:07",
      accumulativeTime: "01:33",
    },
    {
      order: 37,
      code: "KYD",
      name: "KAYDALE",
      arrivalTime: "06:37",
      departureTime: "06:37",
      runTime: "00:10",
      accumulativeTime: "01:43",
    },
    {
      order: 39,
      code: "KOT",
      name: "KLIPPOORTJIE",
      arrivalTime: "06:42",
      departureTime: "06:42",
      runTime: "00:05",
      accumulativeTime: "01:48",
    },
    {
      order: 41,
      code: "HGR",
      name: "HEIDELBERGT",
      arrivalTime: "06:46",
      departureTime: "06:46",
      runTime: "00:04",
      accumulativeTime: "01:52",
    },
    {
      order: 43,
      code: "KXL",
      name: "KRAAL",
      arrivalTime: "06:55",
      departureTime: "06:55",
      runTime: "00:09",
      accumulativeTime: "02:01",
    },
    {
      order: 45,
      code: "SYU",
      name: "SPRUYTSRUS",
      arrivalTime: "07:06",
      departureTime: "07:06",
      runTime: "00:11",
      accumulativeTime: "02:12",
    },
    {
      order: 47,
      code: "FTA",
      name: "FORTUNA",
      arrivalTime: "07:17",
      departureTime: "07:17",
      runTime: "00:11",
      accumulativeTime: "02:23",
    },
    {
      order: 49,
      code: "BOR",
      name: "BALFOURNORTH",
      arrivalTime: "07:27",
      departureTime: "07:27",
      runTime: "00:09",
      accumulativeTime: "02:33",
    },
    {
      order: 51,
      code: "SCW",
      name: "SPRUCEWELL",
      arrivalTime: "07:38",
      departureTime: "07:38",
      runTime: "00:11",
      accumulativeTime: "02:44",
    },
    {
      order: 53,
      code: "GDR",
      name: "GREYLINGSTAD",
      arrivalTime: "07:51",
      departureTime: "07:51",
      runTime: "00:13",
      accumulativeTime: "02:57",
    },
    {
      order: 55,
      code: "TKW",
      name: "TEAKWORTH",
      arrivalTime: "08:02",
      departureTime: "08:02",
      runTime: "00:11",
      accumulativeTime: "03:08",
    },
    {
      order: 57,
      code: "BPT",
      name: "BEYTELPLAATS",
      arrivalTime: "08:10",
      departureTime: "08:10",
      runTime: "00:08",
      accumulativeTime: "03:16",
    },
    {
      order: 59,
      code: "VAL",
      name: "VAL",
      arrivalTime: "08:19",
      departureTime: "08:19",
      runTime: "00:09",
      accumulativeTime: "03:25",
    },
    {
      order: 61,
      code: "CDM",
      name: "CEDARMONT",
      arrivalTime: "08:28",
      departureTime: "08:28",
      runTime: "00:09",
      accumulativeTime: "03:34",
    },
    {
      order: 63,
      code: "HLE",
      name: "HOLMDENE",
      arrivalTime: "08:37",
      departureTime: "08:37",
      runTime: "00:09",
      accumulativeTime: "03:43",
    },
    {
      order: 65,
      code: "EMT",
      name: "ELMTREE",
      arrivalTime: "08:49",
      departureTime: "08:49",
      runTime: "00:11",
      accumulativeTime: "03:55",
    },
    {
      order: 67,
      code: "SNR",
      name: "STANDERTON",
      arrivalTime: "09:05",
      departureTime: "09:05",
      runTime: "00:16",
      accumulativeTime: "04:11",
    },
    {
      order: 69,
      code: "FIR",
      name: "FIRHAM",
      arrivalTime: "09:12",
      departureTime: "09:12",
      runTime: "00:07",
      accumulativeTime: "04:18",
    },
    {
      order: 71,
      code: "KMI",
      name: "KROMDRAAI",
      arrivalTime: "09:25",
      departureTime: "09:25",
      runTime: "00:12",
      accumulativeTime: "04:31",
    },
    {
      order: 73,
      code: "KHL",
      name: "KANONHEUWEL",
      arrivalTime: "09:33",
      departureTime: "09:33",
      runTime: "00:08",
      accumulativeTime: "04:39",
    },
    {
      order: 75,
      code: "PRD",
      name: "PLATRAND",
      arrivalTime: "09:42",
      departureTime: "09:42",
      runTime: "00:09",
      accumulativeTime: "04:48",
    },
    {
      order: 77,
      code: "RHF",
      name: "RUSTHOF",
      arrivalTime: "09:52",
      departureTime: "09:52",
      runTime: "00:10",
      accumulativeTime: "04:58",
    },
    {
      order: 79,
      code: "KPA",
      name: "KOPPIEALLEEN",
      arrivalTime: "09:59",
      departureTime: "09:59",
      runTime: "00:06",
      accumulativeTime: "05:05",
    },
    {
      order: 81,
      code: "PEK",
      name: "PERDEKOP",
      arrivalTime: "10:05",
      departureTime: "10:05",
      runTime: "00:06",
      accumulativeTime: "05:11",
    },
    {
      order: 83,
      code: "EPT",
      name: "ELANDSPOORT",
      arrivalTime: "10:12",
      departureTime: "10:12",
      runTime: "00:07",
      accumulativeTime: "05:18",
    },
    {
      order: 85,
      code: "PMD",
      name: "PALMFORD",
      arrivalTime: "10:18",
      departureTime: "10:18",
      runTime: "00:06",
      accumulativeTime: "05:24",
    },
    {
      order: 87,
      code: "BWK",
      name: "BEECHWICK",
      arrivalTime: "10:26",
      departureTime: "10:26",
      runTime: "00:08",
      accumulativeTime: "05:32",
    },
    {
      order: 89,
      code: "SDU",
      name: "SANDSPRUIT",
      arrivalTime: "10:36",
      departureTime: "10:36",
      runTime: "00:10",
      accumulativeTime: "05:42",
    },
    {
      order: 91,
      code: "VUS",
      name: "VOORUITSIG",
      arrivalTime: "10:51",
      departureTime: "10:51",
      runTime: "00:15",
      accumulativeTime: "05:57",
    },
    {
      order: 93,
      code: "CVS",
      name: "CLAVIS",
      arrivalTime: "11:07",
      departureTime: "11:07",
      runTime: "00:16",
      accumulativeTime: "06:13",
    },
    {
      order: 95,
      code: "LGK",
      name: "LANGSNEK",
      arrivalTime: "11:15",
      departureTime: "11:15",
      runTime: "00:07",
      accumulativeTime: "06:21",
    },
    {
      order: 97,
      code: "MPP",
      name: "MOUNTPROSPECT",
      arrivalTime: "11:29",
      departureTime: "11:29",
      runTime: "00:14",
      accumulativeTime: "06:35",
    },
    {
      order: 99,
      code: "IGO",
      name: "INGOGO",
      arrivalTime: "11:57",
      departureTime: "11:57",
      runTime: "00:28",
      accumulativeTime: "07:03",
    },
    {
      order: 101,
      code: "CTF",
      name: "CLONTARF",
      arrivalTime: "12:08",
      departureTime: "12:08",
      runTime: "00:11",
      accumulativeTime: "07:14",
    },
    {
      order: 103,
      code: "WKM",
      name: "WYKOM",
      arrivalTime: "12:20",
      departureTime: "12:20",
      runTime: "00:12",
      accumulativeTime: "07:26",
    },
    {
      order: 105,
      code: "SLL",
      name: "SIGNALHILL",
      arrivalTime: "12:29",
      departureTime: "12:29",
      runTime: "00:09",
      accumulativeTime: "07:35",
    },
    {
      order: 107,
      code: "NCR",
      name: "NCS-STASIE",
      arrivalTime: "12:37",
      departureTime: "12:37",
      runTime: "00:08",
      accumulativeTime: "07:43",
    },
    {
      order: 109,
      code: "NCS",
      name: "NEWCASTLE",
      arrivalTime: "12:38",
      departureTime: "13:09",
      runTime: "00:01",
      accumulativeTime: "07:44",
    },
    {
      order: 111,
      code: "NGN",
      name: "NGAGANE",
      arrivalTime: "13:30",
      departureTime: "13:30",
      runTime: "00:21",
      accumulativeTime: "08:05",
    },
    {
      order: 113,
      code: "BLG",
      name: "BALLENGEICH",
      arrivalTime: "13:35",
      departureTime: "13:35",
      runTime: "00:05",
      accumulativeTime: "08:10",
    },
    {
      order: 115,
      code: "DHR",
      name: "DANNHAUSER",
      arrivalTime: "13:59",
      departureTime: "13:59",
      runTime: "00:23",
      accumulativeTime: "08:34",
    },
    {
      order: 117,
      code: "HSP",
      name: "HATTINGSPRUIT",
      arrivalTime: "14:12",
      departureTime: "14:12",
      runTime: "00:13",
      accumulativeTime: "08:47",
    },
    {
      order: 119,
      code: "GJO",
      name: "GLENCOE",
      arrivalTime: "14:36",
      departureTime: "14:36",
      runTime: "00:24",
      accumulativeTime: "09:11",
    },
    {
      order: 121,
      code: "UTK",
      name: "UITHOEK",
      arrivalTime: "14:58",
      departureTime: "14:58",
      runTime: "00:22",
      accumulativeTime: "09:33",
    },
    {
      order: 123,
      code: "WBK",
      name: "WASBANK",
      arrivalTime: "15:07",
      departureTime: "15:07",
      runTime: "00:09",
      accumulativeTime: "09:42",
    },
    {
      order: 125,
      code: "WSN",
      name: "WESSELSNEK",
      arrivalTime: "15:17",
      departureTime: "15:17",
      runTime: "00:10",
      accumulativeTime: "09:52",
    },
    {
      order: 127,
      code: "ELL",
      name: "ELANDSLAAGTE",
      arrivalTime: "15:31",
      departureTime: "15:31",
      runTime: "00:13",
      accumulativeTime: "10:06",
    },
    {
      order: 129,
      code: "PPW",
      name: "PEPWORTH",
      arrivalTime: "15:42",
      departureTime: "15:42",
      runTime: "00:11",
      accumulativeTime: "10:17",
    },
    {
      order: 131,
      code: "DSL",
      name: "DANSKRAAL",
      arrivalTime: "16:05",
      departureTime: "16:05",
      runTime: "00:23",
      accumulativeTime: "10:40",
    },
    {
      order: 133,
      code: "LAY",
      name: "DSL-LADYSMITH(N)",
      arrivalTime: "16:08",
      departureTime: "16:08",
      runTime: "00:03",
      accumulativeTime: "10:43",
    },
    {
      order: 135,
      code: "UMB",
      name: "UMBULWANA",
      arrivalTime: "16:18",
      departureTime: "16:18",
      runTime: "00:10",
      accumulativeTime: "10:53",
    },
    {
      order: 137,
      code: "PIT",
      name: "PIETERS",
      arrivalTime: "16:25",
      departureTime: "16:25",
      runTime: "00:06",
      accumulativeTime: "11:00",
    },
    {
      order: 139,
      code: "CSO",
      name: "COLENSO",
      arrivalTime: "16:37",
      departureTime: "16:37",
      runTime: "00:12",
      accumulativeTime: "11:12",
    },
    {
      order: 141,
      code: "CVL",
      name: "CHIEVELEY",
      arrivalTime: "16:49",
      departureTime: "16:49",
      runTime: "00:12",
      accumulativeTime: "11:24",
    },
    {
      order: 143,
      code: "FRH",
      name: "FRERE",
      arrivalTime: "17:00",
      departureTime: "17:00",
      runTime: "00:10",
      accumulativeTime: "11:35",
    },
    {
      order: 145,
      code: "ENE",
      name: "ENNERSDALE",
      arrivalTime: "17:12",
      departureTime: "17:12",
      runTime: "00:12",
      accumulativeTime: "11:47",
    },
    {
      order: 147,
      code: "ECT",
      name: "ESTCOURT",
      arrivalTime: "17:23",
      departureTime: "17:23",
      runTime: "00:11",
      accumulativeTime: "11:58",
    },
    {
      order: 149,
      code: "BCH",
      name: "BEACONHILL",
      arrivalTime: "17:35",
      departureTime: "17:35",
      runTime: "00:12",
      accumulativeTime: "12:10",
    },
    {
      order: 151,
      code: "LOW",
      name: "LOWLANDS",
      arrivalTime: "17:42",
      departureTime: "17:42",
      runTime: "00:07",
      accumulativeTime: "12:17",
    },
    {
      order: 153,
      code: "HCT",
      name: "HIDCOTE",
      arrivalTime: "17:57",
      departureTime: "17:57",
      runTime: "00:14",
      accumulativeTime: "12:32",
    },
    {
      order: 155,
      code: "MRR",
      name: "MOOIRIVIER",
      arrivalTime: "18:05",
      departureTime: "18:05",
      runTime: "00:08",
      accumulativeTime: "12:40",
    },
    {
      order: 157,
      code: "ROA",
      name: "ROSETTA",
      arrivalTime: "18:17",
      departureTime: "18:17",
      runTime: "00:12",
      accumulativeTime: "12:52",
    },
    {
      order: 159,
      code: "NRP",
      name: "NOTTINGHAMROA",
      arrivalTime: "18:24",
      departureTime: "18:24",
      runTime: "00:07",
      accumulativeTime: "12:59",
    },
    {
      order: 161,
      code: "BGN",
      name: "BALGOWAN",
      arrivalTime: "18:47",
      departureTime: "18:47",
      runTime: "00:23",
      accumulativeTime: "13:22",
    },
    {
      order: 163,
      code: "LGO",
      name: "LIDGETTON",
      arrivalTime: "18:59",
      departureTime: "18:59",
      runTime: "00:11",
      accumulativeTime: "13:34",
    },
    {
      order: 165,
      code: "DRE",
      name: "DARGLE",
      arrivalTime: "19:05",
      departureTime: "19:05",
      runTime: "00:06",
      accumulativeTime: "13:40",
    },
    {
      order: 167,
      code: "LIR",
      name: "LIONSRIVER",
      arrivalTime: "19:12",
      departureTime: "19:12",
      runTime: "00:06",
      accumulativeTime: "13:47",
    },
    {
      order: 169,
      code: "TDI",
      name: "TWEEDIE",
      arrivalTime: "19:20",
      departureTime: "19:20",
      runTime: "00:08",
      accumulativeTime: "13:55",
    },
    {
      order: 171,
      code: "MRV",
      name: "MERRIVALE",
      arrivalTime: "19:30",
      departureTime: "19:30",
      runTime: "00:09",
      accumulativeTime: "14:05",
    },
    {
      order: 173,
      code: "CDA",
      name: "CEDARA(N)",
      arrivalTime: "19:37",
      departureTime: "19:37",
      runTime: "00:07",
      accumulativeTime: "14:12",
    },
    {
      order: 175,
      code: "BHN",
      name: "BOUGHTON",
      arrivalTime: "20:04",
      departureTime: "20:04",
      runTime: "00:27",
      accumulativeTime: "14:39",
    },
    {
      order: 177,
      code: "PZB",
      name: "PIETERMARITZB",
      arrivalTime: "20:17",
      departureTime: "20:38",
      runTime: "00:13",
      accumulativeTime: "14:52",
    },
    {
      order: 179,
      code: "NPR",
      name: "NAPIER (N)",
      arrivalTime: "20:46",
      departureTime: "20:46",
      runTime: "00:08",
      accumulativeTime: "15:00",
    },
    {
      order: 181,
      code: "PNC",
      name: "PENTRICH",
      arrivalTime: "20:50",
      departureTime: "20:50",
      runTime: "00:04",
      accumulativeTime: "15:04",
    },
    {
      order: 183,
      code: "ASR",
      name: "ASHBURTON",
      arrivalTime: "21:02",
      departureTime: "21:02",
      runTime: "00:12",
      accumulativeTime: "15:16",
    },
    {
      order: 185,
      code: "ULS",
      name: "UMLAASROAD",
      arrivalTime: "21:15",
      departureTime: "21:15",
      runTime: "00:12",
      accumulativeTime: "15:29",
    },
    {
      order: 187,
      code: "CAP",
      name: "CAMPERDOWN",
      arrivalTime: "21:19",
      departureTime: "21:19",
      runTime: "00:04",
      accumulativeTime: "15:33",
    },
    {
      order: 189,
      code: "COR",
      name: "CATORIDGE",
      arrivalTime: "21:27",
      departureTime: "21:47",
      runTime: "00:07",
      accumulativeTime: "15:41",
    },
    {
      order: 191,
      code: "GDL",
      name: "GEORGEDALE",
      arrivalTime: "22:07",
      departureTime: "22:07",
      runTime: "00:20",
      accumulativeTime: "16:01",
    },
    {
      order: 193,
      code: "KTA",
      name: "KWATANDAZA",
      arrivalTime: "22:10",
      departureTime: "22:10",
      runTime: "00:03",
      accumulativeTime: "16:04",
    },
    {
      order: 195,
      code: "HDE",
      name: "HAMMARSDALE",
      arrivalTime: "22:17",
      departureTime: "22:17",
      runTime: "00:06",
      accumulativeTime: "16:11",
    },
    {
      order: 197,
      code: "CFD",
      name: "CLIFFDALE",
      arrivalTime: "22:28",
      departureTime: "22:28",
      runTime: "00:11",
      accumulativeTime: "16:22",
    },
    {
      order: 199,
      code: "NNI",
      name: "NSHONGWENI",
      arrivalTime: "22:38",
      departureTime: "22:38",
      runTime: "00:10",
      accumulativeTime: "16:32",
    },
    {
      order: 201,
      code: "DLE",
      name: "DELVILLEWOOD",
      arrivalTime: "22:43",
      departureTime: "22:43",
      runTime: "00:05",
      accumulativeTime: "16:37",
    },
    {
      order: 203,
      code: "KNZ",
      name: "KWANDENGEZI",
      arrivalTime: "22:51",
      departureTime: "22:51",
      runTime: "00:08",
      accumulativeTime: "16:45",
    },
    {
      order: 205,
      code: "DAS",
      name: "DASSENHOEK",
      arrivalTime: "22:55",
      departureTime: "22:55",
      runTime: "00:04",
      accumulativeTime: "16:49",
    },
    {
      order: 207,
      code: "SNU",
      name: "SITUNDUHILLS",
      arrivalTime: "22:58",
      departureTime: "22:58",
      runTime: "00:03",
      accumulativeTime: "16:52",
    },
    {
      order: 209,
      code: "TWD",
      name: "THORNWOOD",
      arrivalTime: "23:02",
      departureTime: "23:02",
      runTime: "00:04",
      accumulativeTime: "16:56",
    },
    {
      order: 211,
      code: "MRH",
      name: "MARIANNHILL",
      arrivalTime: "23:08",
      departureTime: "23:08",
      runTime: "00:05",
      accumulativeTime: "17:02",
    },
    {
      order: 213,
      code: "KRW",
      name: "KLAARWATER",
      arrivalTime: "23:14",
      departureTime: "23:14",
      runTime: "00:06",
      accumulativeTime: "17:08",
    },
    {
      order: 215,
      code: "SCS",
      name: "SHALLCROSS",
      arrivalTime: "23:21",
      departureTime: "23:21",
      runTime: "00:06",
      accumulativeTime: "17:15",
    },
    {
      order: 217,
      code: "BTQ",
      name: "BURLINGTON",
      arrivalTime: "23:27",
      departureTime: "23:27",
      runTime: "00:06",
      accumulativeTime: "17:21",
    },
    {
      order: 219,
      code: "CAV",
      name: "CAVENDISH",
      arrivalTime: "23:30",
      departureTime: "23:30",
      runTime: "00:03",
      accumulativeTime: "17:24",
    },
    {
      order: 221,
      code: "MTV",
      name: "MOUNTVERNON",
      arrivalTime: "23:38",
      departureTime: "23:38",
      runTime: "00:07",
      accumulativeTime: "17:32",
    },
    {
      order: 223,
      code: "BTH",
      name: "BOOTH",
      arrivalTime: "23:46",
      departureTime: "23:46",
      runTime: "00:08",
      accumulativeTime: "17:40",
    },
    {
      order: 225,
      code: "CWD",
      name: "CLAIRWOOD",
      arrivalTime: "23:51",
      departureTime: "23:51",
      runTime: "00:05",
      accumulativeTime: "17:45",
    },
    {
      order: 227,
      code: "JBS",
      name: "JACOBS",
      arrivalTime: "23:56",
      departureTime: "23:56",
      runTime: "00:05",
      accumulativeTime: "17:50",
    },
    {
      order: 229,
      code: "WWH",
      name: "WENTWORTHPARK",
      arrivalTime: "00:00",
      departureTime: "00:00",
      runTime: "00:04",
      accumulativeTime: "17:54",
    },
    {
      order: 231,
      code: "KGX",
      name: "KINGSREST",
      arrivalTime: "00:12",
      departureTime: "00:12",
      runTime: "00:12",
      accumulativeTime: "18:06",
    },
  ],
}

